namespace DG.Cryptography.Random
{
    /// <summary>
    /// <para>Provides a way to fill an array with randomly generated bytes.</para>
    /// <para>Note that this interface provides extended functionality through <see cref="IRandomNumberProviderExtensions"/>.</para> 
    /// </summary>
    public interface IRandomNumberProvider
    {
        /// <summary>
        /// Fills an array of bytes with a sequence of randomly generated values.
        /// </summary>
        /// <param name="buffer"></param>
        void GetNext(byte[] buffer);
    }
}
